# Generated by Django 3.2.5 on 2021-10-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_controller', models.CharField(max_length=150, verbose_name='Пристрій керування')),
                ('has_item', models.IntegerField(verbose_name='Кількість підключених предметів до цього пристрою')),
            ],
            options={
                'verbose_name': 'Засіб керування',
                'verbose_name_plural': 'Засоби керування',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва елементу')),
                ('title', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.controls')),
            ],
        ),
    ]
