# Generated by Django 3.2.5 on 2021-10-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Пристрій', 'verbose_name_plural': 'Пристрої'},
        ),
        migrations.AlterField(
            model_name='items',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.controls'),
        ),
    ]
