# Generated by Django 3.2.5 on 2021-10-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211028_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.controls'),
        ),
    ]
