# Generated by Django 3.2.5 on 2021-10-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_items_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.controls'),
        ),
    ]
